dist: trusty
sudo: required
language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q
  - sudo apt-get remove -qy lxd lxd-client
  - sudo apt-get install snapd libsodium-dev -y
install:
  - sudo snap install lxd || true  # ignore failures so that unit tests will still run, at least
  - sudo snap install jq || true
  - sudo snap install juju --classic --$JUJU_CHANNEL || true
  - sudo snap install juju-wait --classic || true
  - pip install tox-travis
env:
  global: >
    TEST_AGENTS='{"agents":[{"url":"https://api.staging.jujucharms.com/identity","username":"libjuju-ci@yellow"}],"key":{"private":"88OOCxIHQNguRG7zFg2y2Hx5Ob0SeVKKBRnjyehverc=","public":"fDn20+5FGyN2hYO7z0rFUyoHGUnfrleslUNtoYsjNSs="}}'
    PATH="/snap/bin:$PATH"
  matrix:
    - JUJU_CHANNEL=stable
    - JUJU_CHANNEL=edge
before_script:
  - sudo bash -c 'for i in 5 10 15 30; do [[ -e /var/snap/lxd/common/lxd/unix.socket ]] && break; sleep $i; done'
  - sudo addgroup lxd || true
  - sudo usermod -a -G lxd $USER || true
  - sudo -E sudo -u $USER -E bash -c 'lxc storage create default dir'
  - sudo lxd init --auto || true
  - sudo -E sudo -u $USER -E bash -c 'lxc config set core.https_address "[::]"'
  - sudo -E sudo -u $USER -E bash -c 'for i in 5 10 15 30; do [[ "$(lxc query --wait /1.0 | jq .environment.addresses)" != "[]" ]] && break; sleep $i; done'
  - sudo -E sudo -u $USER -E bash -c 'sudo mkdir /var/snap/lxd/common/lxd/storage-pools/juju-zfs'
  - sudo -E sudo -u $USER -E bash -c 'sudo lxc storage create juju-zfs dir source=/var/snap/lxd/common/lxd/storage-pools/juju-zfs' # Horrible workaround to LP Bug #1738614
script:
  - sudo -E sudo -u $USER -E juju bootstrap localhost test --config 'identity-url=https://api.staging.jujucharms.com/identity' --config 'allow-model-access=true'
  - tox -e py3,integration,serial
